#!/bin/sh
# vim: set ft=sh sw=2 et :

install_brew() {
  # Proudly borrowed from:
  # https://github.com/duckfullstop/dotfiles/blob/f734eea399a7ccd1c25b57242997e79f230abc4d/.config/yadm/bootstrap

  # install Homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing Homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
		export PATH="/opt/homebrew/bin:$PATH"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating Homebrew bundle"
    brew bundle --global
    brew bundle cleanup --global --force
  fi
}

configure_elvish() {
  elvish $HOME/.config/elvish/bootstrap.elv
}

configure_sudo() {
  sed "s/^#auth/auth/" /etc/pam.d/sudo_local.template | sudo tee /etc/pam.d/sudo_local > /dev/null
}

configure_dock() {
  # Dock > Automatically hide and show the Dock
  defaults write com.apple.dock autohide -bool true
  
  # Show recent applications in Dock
  defaults write com.apple.dock "show-recents" -bool false

  dockutil --no-restart --remove all
  dockutil --no-restart --add "/Applications/Safari.app"
  dockutil --no-restart --add "/Applications/Messages.app"
  dockutil --no-restart --add "/Applications/Mail.app"
  dockutil --no-restart --add "/Applications/Calendar.app"
  dockutil --no-restart --add "/Applications/Music.app"
  dockutil --no-restart --add "/Applications/Visual Studio Code.app"
  dockutil --no-restart --add "/Applications/ChatGPT.app"
  dockutil --no-restart --add "/Applications/Ghostty.app"
  dockutil --no-restart --add "~/Downloads" --view fan --display stack
}

configure_macos() {
  # Windows & Apps > Prefer tabs when opening documents
  defaults write -globalDomain AppleWindowTabbingMode -string "always"

  # Menu Bar Only > Clock Options > Show seconds
  defaults write "com.apple.menuextra.clock" ShowSeconds -bool true

  # Finder > View > Show Path Bar
  defaults write com.apple.finder ShowPathbar -bool true

  # Finder > View > As List
  defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

  # Show all filename extensions
  defaults write NSGlobalDomain AppleShowAllExtensions -bool true

  # Show wraning before changing an extension
  defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

  # Tap to click
  defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
  defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true

  # Double-click title bar to zoom
  defaults write -globalDomain AppleActionOnDoubleClick -string "Zoom"

  # Set fast key repeat rate
  defaults write -globalDomain KeyRepeat -int 2

}

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
  install_brew
  configure_elvish
  configure_sudo
  configure_dock
  configure_macos
  
  killall Dock
  killall Finder
fi
