#!/bin/sh
# vim: set ft=sh sw=2 et :

install_brew() {
  # Proudly borrowed from:
  # https://github.com/duckfullstop/dotfiles/blob/f734eea399a7ccd1c25b57242997e79f230abc4d/.config/yadm/bootstrap

  # install Homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing Homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating Homebrew bundle"
    brew bundle --global
  fi
}

configure_elvish() {
  elvish $HOME/.config/elvish/bootstrap.elv
}

configure_alacritty() {
  # Remove that ugly default icon
  ln -sf $HOME/.config/alacritty/alacritty.icns /Applications/Alacritty.app/Contents/Resources/alacritty.icns
}

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
  install_brew
  configure_elvish
  configure_alacritty
fi
